name: Deploy
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    environment: main
    steps:
      - uses: actions/checkout@v3
      - name: Copy repository contents via scp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm test
      - run: cd var/www/abk-api/
      - run: git pull origin main
      - run: git status
      - run: npm install
      - run: sudo docker ps
      - run: echo "Deployed successfully!"
      - run: echo ls
      - run: echo "test --------------------------------"