name: Deploy Prod
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    environment: main
    steps:
      - uses: actions/checkout@v3
      - name: Copy repository contents via scp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
        env:
          PORT: ${{ secrets.PORT }}
      - run: git pull origin main
      - run: |
          touch .env
          echo PORT="$PORT" >> .env
          echo MONGO_DB_URL="$MONGO_DB_URL" >> .env
        env:
          PORT: ${{ secrets.API_PORT_3000 }}
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
      - run: npm run docker:build-prod
      - run: npm run docker:update-prod
      - run: npm run docker:run-prod
      - run: docker ps
      - run: echo "Deployed successfully!"