name: Deploy Develop
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
jobs:
  deploy:
    runs-on: self-hosted
    environment: main
    steps:
      - uses: actions/checkout@v3
      - name: Copy repository contents via scp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
        env:
          PORT: ${{ secrets.API_PORT_3000 }}
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
      - run: git pull origin develop
      - run: |
          touch .env
          echo PORT="${{PORT}}" >> .env
          echo MONGO_DB_URL="${{MONGO_DB_URL}}" >> .env
          echo "cat .env"
          cat .env
      - run: npm run docker:build-dev
      - run: npm run docker:update-dev
      - run: npm run docker:run-dev
      - run: docker ps
      - run: echo "Deployed successfully!"